### ISSUE TITLE
Develop basic concept of event management

### ISSUE THREAD

**Issue by azasypkin** [vargin/vargin#11]
Scope:
- User should be able to set event handlers for the components;
- User should be able to connect events with actions;
- As the first step we'd like to:
  *\* Change label name on button click;
  - Change button color on button click;
  - Change label background color on hover.

Dependencies:
- [x] <s>Introduce support of default properties and styles (https://github.com/vargin/vargin/issues/14)</s>
- [x] <s>[Events] Implement basic Action entity (https://github.com/vargin/vargin/issues/13)</s>
- [x] <s>[Events] Implement MessageChannel and Message (https://github.com/vargin/vargin/issues/12)</s>

**Comment by azasypkin** [comment]
blocks https://github.com/vargin/vargin/issues/11

**Comment by azasypkin** [comment]
Scope has changed: we'll just cover basic event/event handlers infrastructure in this bug and return back once "Demo/Live" mode is ready so that we can test event handlers.
